version: 2.1 

executors:
  node:
    docker: 
      - image: circleci/node:latest

jobs:
  surge:
    executor: 
      name: node
    steps: 
      - checkout 
      - run: npm install surge
      - run: ./node_modules/surge/lib/cli.js --project ./ --domain $DOMAIN.surge.sh


workflows:
  deploy:
    jobs:
      - surge