version: 2.1 

orbs:
  welcome: circleci/welcome-orb@0.4.1

executors:
  node:
    docker: 
      - image: circleci/node:latest

jobs:
  surge-install:
    executor: 
      name: node
    steps: 
      - checkout 
      - run: npm install surge
      - run: ./node_modules/surge/lib/cli.js --project ./ --domain $SURGE-DOMAIN.surge.sh


workflows:
  hello:
    jobs: 
      - welcome/run
  main:
    jobs:
      - surge-install